universe        = vanilla
executable      = run.sh
arguments       = $(config)

request_gpus    = 1
request_cpus    = 2
request_memory  = 16384
require_gpus = (Capability >= 7.5)
# require_gpus = regexp("A100", GPUs_DeviceName)
+JobFlavour     = "longlunch"

output          = logs/$(Cluster).$(Process).out
error           = logs/$(Cluster).$(Process).err
log             = logs/$(Cluster).$(Process).log

MY.SendCredential = True            # for writing in EOS

# notification    = Never # Always / Complete / Error / Never
# notify_user     = ykao@cern.ch
# queue config matching files /eos/home-y/ykao/SWAN_projects/analysis/configs/*.yml

queue config matching files /eos/home-y/ykao/SWAN_projects/analysis/topsbi/condor/configs/*.yml
